services:
  users-service:
    container_name: users-service
    build:
      context: ../../services/users
      dockerfile: Dockerfile.dev
    volumes:
      - ../../services/users:/app
    ports:
      - 8081:8080

  api-gateway:
    image: kong:3.9.1
    container_name: api-gateway
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/kong.yaml
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
    volumes:
      - ./configs/kong/kong.yaml:/kong/kong.yaml:ro
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    depends_on:
      - keycloak
      - users-service

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.2
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./configs/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - 8080:8080
