_format_version: "3.0"
_transform: true

services:
  - name: follow
    url: http://follow-service:8080/
    routes:
      - name: follow-route
        strip_path: true
        paths:
          - /api/v1/follow

  - name: posts
    url: http://posts-service:8080/
    routes:
      - name: posts-route
        strip_path: true
        paths:
          - /api/v1/posts

  - name: timeline
    url: http://timeline-service:8080/
    routes:
      - name: timeline-route
        strip_path: true
        paths:
          - /api/v1/timeline

  - name: users
    url: http://users-service:8080/
    routes:
      - name: users-route
        strip_path: true
        paths:
          - /api/v1/users


